version: '3.8'

services:
  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-mcp-test
    environment:
      ORACLE_PASSWORD: Oracle123!
      ORACLE_DATABASE: TESTDB
      ORACLE_USER: testuser
      ORACLE_PASSWORD_USER: TestUser123!
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init-scripts:/container-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data:
